apiVersion: v1
kind: ServiceAccount
metadata:
  name: fabgitops-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabgitops-operator
rules:
  # Manage IndustrialPLC resources
  - apiGroups:
      - fabgitops.io
    resources:
      - industrialplcs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - fabgitops.io
    resources:
      - industrialplcs/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - fabgitops.io
    resources:
      - industrialplcs/finalizers
    verbs:
      - update
  # Manage events
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # Read configmaps and secrets
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabgitops-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fabgitops-operator
subjects:
  - kind: ServiceAccount
    name: fabgitops-operator
    namespace: default
