apiVersion: fabgitops.io/v1
kind: IndustrialPLC
metadata:
  name: plc-line-1
  namespace: default
  labels:
    app: fabgitops
    line: "1"
spec:
  deviceAddress: "mock-plc.default.svc.cluster.local"
  port: 5502
  targetRegister: 4001
  targetValue: 2500
  pollIntervalSecs: 5
  autoCorrect: true
  tags:
    - production
    - temperature-control
    - critical
---
apiVersion: fabgitops.io/v1
kind: IndustrialPLC
metadata:
  name: plc-line-2
  namespace: default
  labels:
    app: fabgitops
    line: "2"
spec:
  deviceAddress: "mock-plc.default.svc.cluster.local"
  port: 5502
  targetRegister: 4001
  targetValue: 2500
  pollIntervalSecs: 10
  autoCorrect: true
  tags:
    - production
    - pressure-control
